apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: openhack-vault-sqlpass
  namespace: tripinsights
spec:
  provider: azure
  parameters:
    keyvaultName: "openhack-vault"       # The name of the Azure Key Vault
    usePodIdentity: "true"               # [OPTIONAL] if not provided, will default to "false". Set to "true" if using pod identities.
    useVMManagedIdentity: "false"        # [OPTIONAL] if not provided, will default to "false". Set to "true" if using managed identities.
    userAssignedIdentityID: ""           # The clientId of the addon-created managed identity
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: SQLPassword         # In this example, 'ExampleSecret'   
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
          objectAlias: SQL_PASSWORD
    tenantId: "1e66ea18-3eab-4c72-9397-c1fdbdfd0de3"               # the tenant ID containing the Azure Key Vault instance
