apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: tripinsights
spec:
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryfqd3481.azurecr.io/tripinsights/trips:1.0
        env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: dbaccess
                key: username
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbaccess
                key: password
          - name: SQL_SERVER
            value: sqlserverfqd3481.database.windows.net
          - name: SQL_DBNAME
            value: mydrivingDB
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: tripinsights
spec:
  selector:
    app: trips
  ports:
  - port: 80
    targetPort: 80
