apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: tripinsights
spec:
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryfqd3481.azurecr.io/tripinsights/user-java:1.0
        env:
          - name: SQL_USER
            value: sqladminfQd3481
          - name: SQL_SERVER
            value: sqlserverfqd3481.database.windows.net:1433
          - name: SQL_DBNAME
            value: mydrivingDB
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "openhack-vault-sqlpass"
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: tripinsights
spec:
  selector:
    app: user-java
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-java
  namespace: tripinsights
  labels:
    name: user-java
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/health-probe-path: /api/user-java/healthcheck
spec:
  rules:
  - host: team5.northeurope.cloudapp.azure.com
    http:
      paths:
      - pathType: Prefix
        path: "/api/user-java/healthcheck"
        backend:
          service:
            name: user-java
            port: 
              number: 80
      - pathType: Prefix
        path: "/api/user-java/*"
        backend:
          service:
            name: user-java
            port: 
              number: 80
